KingdomDemandクラスの実装
KingdomCraft-1/KingdomCraft pull request #253
Opened 2016-12-26 02:35 UTC by Moto0116

issue #248

2017-01-05 07:48 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/KingdomStatusWindow/KingdomDemandUI/KingdomDemandUI.cpp
> +			Vertex[i].Color = 0xff0000ff;
色が状態かなんかで変わるんだったら各状態の色を定数で持ってたほうがみやすいと思う

2017-01-06 02:32 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/KingdomStatusWindow/KingdomDemandUI/KingdomDemandUI.cpp
> +			Vertex[i].Color = 0xff0000ff;
指摘を受けて修正しました。
カラー値は定数にして管理するよう変更しました。

2017-01-07 01:52 UTC, Keitaro0408 requested changes

2017-01-07 01:52 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/KingdomStatusWindow/KingdomDemandUI/KingdomDemandUI.h
> +	struct KINGDOMDEMAND
このクラス内でしか使ってないしprivateで良くない？

2017-01-07 04:53 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/KingdomStatusWindow/KingdomDemandUI/KingdomDemandUI.h
> +	struct KINGDOMDEMAND
GameDataManager内で使うつもりやったからpublicに置いてる。

2017-01-07 04:55 UTC, Keitaro0408 approved these changes

2017-01-07 04:57 UTC, Keitaro0408 commented
確認しました。
コミットまとめお願いします

2017-01-07 07:35 UTC, Moto0116 commented
コミットログまとめました。
確認お願いします。

2017-01-07 07:36 UTC, Keitaro0408 commented
確認したので合流しておきます

2017-01-07 07:36 UTC, merged