GameTimeManagerクラスの実装
KingdomCraft-1/KingdomCraft pull request #259
Opened 2016-12-28 05:37 UTC by Moto0116

**追加機能**
- GameTimeManagerクラスの実装
- GameTimeEventクラスの実装
- GameDataManagerにゲーム時間の追加

2016-12-28 17:23 UTC, Moto0116 commented
作業完了したのでレビューお願いします。

2017-01-03 03:19 UTC, Keitaro0408 requested changes

2017-01-03 03:19 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/EventManager/Event/GameTimeEvent/GameTimeEvent.h
> +		DECELERATE_OF_TIME,	// 時間の原則
漢字間違い。
あとOFは無くても良いと思う

2017-01-03 05:04 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/EventManager/Event/GameTimeEvent/GameTimeEvent.h
> +		DECELERATE_OF_TIME,	// 時間の原則
指摘を受けた部分を修正しました確認お願いします。

2017-01-05 07:17 UTC, Keitaro0408 requested changes

2017-01-05 07:17 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/GameTimeManager/GameTimeManager.h
> +		PAUSE_STATE,	// 停止状態
~_SPEEDとかのほうがわかりやすいと思う

2017-01-05 07:37 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/GameTimeManager/GameTimeManager.h
> +		PAUSE_STATE,	// 停止状態
指摘を受けた部分を修正しました。
定数部分は~_SPEEDの形に変更したのと、enum名もSPEED_STATEに変更しました。
確認お願いします。

2017-01-05 07:37 UTC, Keitaro0408 commented
確認しました、コミットまとめお願いします

2017-01-05 07:46 UTC, Moto0116 commented
コミットログまとめときました。

2017-01-05 07:48 UTC, Keitaro0408 approved these changes

2017-01-05 07:48 UTC, Keitaro0408 commented
合流しておきます

2017-01-05 07:48 UTC, merged