MousePosConverterの実装
KingdomCraft-1/KingdomCraft pull request #285
Opened 2017-01-12 08:47 UTC by Keitaro0408

**実装内容**
* マウスの指している地面の座標を格納しているクラス

issue #284

2017-01-17 03:10 UTC, Moto0116 requested changes

2017-01-17 03:10 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/MousePosConverter/MousePosConverter.h
> +	* マウスの座標を地面の座標に変換する
スペース入れてほしい

2017-01-17 03:10 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/MousePosConverter/MousePosConverter.h
> +	*/
MousePosConverterなんやから_mousePosとかでいいと思う

2017-01-17 03:10 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/MainCamera/MainCamera.h
> +	inline Camera* const GetCamera()
カメラを直接返す必要はない気がする。
MainCameraで行列返すようにしたらいいし

2017-01-17 03:10 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/MainCamera/MainCamera.h
> +		return &Instance;
MainCameraのシングルトンはGameDataManagerと同じ感じがいいと思う。

2017-01-17 03:11 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/MainCamera/MainCamera.cpp
>  const float MainCamera::m_FarPoint = 300000.f;
FarPointは小さいほうに修正しといたらいいと思う

2017-01-17 03:12 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/MainCamera/MainCamera.cpp
>  const float MainCamera::m_FarPoint = 300000.f;
モデルの変更時に修正します

2017-01-17 03:14 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/MousePosConverter/MousePosConverter.h
> +	 * インスタンスを取得する関数
帰り値のコメントもつけとくべきやと思う

2017-01-17 06:51 UTC, Keitaro0408 commented
指摘箇所の修正をしたので確認お願いします

2017-01-17 08:42 UTC, Keitaro0408 commented
修正したので確認お願いします

2017-01-18 01:53 UTC, Moto0116 commented
確認しました。
コミットまとめてください。

2017-01-18 02:07 UTC, Keitaro0408 commented
コミットまとめ完了しました。

2017-01-18 03:42 UTC, Moto0116 approved these changes
確認しました
合流しときます

2017-01-18 03:55 UTC, merged