イベントログ表示クラスの追加
KingdomCraft-1/KingdomCraft pull request #295
Opened 2017-01-17 07:02 UTC by Moto0116

**追加機能**
- GameEventLogWindowクラスの追加
- GameEventクラスの追加
- GameEventListenerクラスの追加

issue #290

2017-01-23 01:38 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/GameEventLogWindow/GameEventLogWindow.cpp
> +
EventMessageControl()の中のswitchでは空白開けてなかったしこっちも無くて良いんじゃない？

2017-01-23 01:41 UTC, Keitaro0408 requested changes

2017-01-23 01:41 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/GameEventLogWindow/GameEventLogWindow.cpp
> +
EventMessageControl()の中のswitchでは空白開けてなかったしこっちも無くて良いんじゃない？

2017-01-28 06:16 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/GameEventLogWindow/GameEventLogWindow.cpp
> +
EventMessageControlはifでくくられてるから空白開けてなくて、こっちは数行にわたっての関数呼び出しで見にくいから空けてる。

2017-01-28 06:36 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/UIManager/GameEventLogWindow/GameEventLogWindow.cpp
> +
分かりました

2017-01-28 06:36 UTC, Keitaro0408 approved these changes

2017-01-28 06:37 UTC, Keitaro0408 commented
確認したので合流しておきます

2017-01-28 06:37 UTC, merged