RoadManager配下の実装
KingdomCraft-1/KingdomCraft pull request #304
Opened 2017-01-18 05:46 UTC by Keitaro0408

**実装内容**
* 道の生成
* ビルドエリアの生成

issue #278

2017-01-21 10:28 UTC, Keitaro0408 commented
Fキーを押してから、道の始点と終点を指定して敷くことが出来るようにしてあります。
確認お願いします

2017-01-21 12:17 UTC, Moto0116 requested changes

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.cpp
> +Road::Road(int _vertexShaderIndex, int _pixelShaderIndex, D3DXVECTOR3* _startPos, D3DXVECTOR3* _endPos) :
ポインタの引数はpを頭につけてください。

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +	bool					 m_isCurve;
m_IsCurveの形にしてください

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.cpp
> +	delete m_pBuildAreaManager;
生成の順序的に考えて、m_pBuildAreaManagerは最後に破棄すべきだと思います

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.cpp
> +	switch (m_Step)
この分岐内の処理は関数化したほうが良いと思う。

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/BuildAreaManager/BuildAreaManager.h
> +	~BuildAreaManager();
関数コメントとクラスコメントを付けてください。

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.cpp
> +	ReleaseVertexLayout();
破棄は生成の逆順でやってください。

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.cpp
> +	DX11Manager::GetInstance()->GetDeviceContext()->Draw(m_VertexNum,0);
ごめん、スペースないのはどうしても気になるから修正しといてほしい。

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +	Road(int _vertexShaderIndex, int _pixelShaderIndex, D3DXVECTOR3* _startPos, D3DXVECTOR3* _endPos);
引数コメントを付けてほしい

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +	 */
返り値コメントを付けてほしい。

2017-01-21 12:17 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Resource/Effect/GameScene/Road.fx
> +	//return g_Texture.Sample(g_Sampler, In.UV);
ここのコメントは残す意味ないと思う、上のUV入れてるのもいらないと思う

2017-01-21 12:27 UTC, Moto0116 requested changes
StartPosとEndPosの値が同じ場合にCreateVertexに入ると、PointNumが0になって、vectorのアクセス時にプログラムが落ちるようになってるので修正お願いします

2017-01-21 12:32 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.cpp
> +			m_StartPos = D3DXVECTOR3(0.f, 0.f, 0.f);
たぶん、Step切り替えるのを忘れてない？

2017-01-22 03:42 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.cpp
> +	switch (m_Step)
分かりました。
分けておくのと道を引く際に判定を追加しておきます。

2017-01-22 03:42 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.cpp
> +	delete m_pBuildAreaManager;
直しておきます

2017-01-22 14:32 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.cpp
> +			m_StartPos = D3DXVECTOR3(0.f, 0.f, 0.f);
忘れていたので直しておきます

2017-01-22 16:24 UTC, Keitaro0408 commented
指摘箇所の修正が完了したので確認お願いします

2017-01-28 05:31 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.h
> +		CREATE_STEP,
最後の要素は「,」つけないでほしいです。

2017-01-28 05:31 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/RoadManager.h
> +	void CreateStep();
関数群は変数の上で定義してください。

2017-01-28 05:38 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +	inline D3DXVECTOR3 EndStartPos()
関数名はGetEndStartPosでは？

2017-01-28 05:39 UTC, Moto0116 requested changes

2017-01-28 05:39 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +		return m_CenterLinePos[m_CenterLinePos.size()];
道の最後をとるのなら、`size() - 1` では？

2017-01-28 05:41 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +	 * @param _dividNum 道の分割数
引数コメントにはin outの情報を乗っけてください

2017-01-28 06:29 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +	inline D3DXVECTOR3 EndStartPos()
GetEndPosに修正しておきます

2017-01-28 06:29 UTC, Keitaro0408 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +		return m_CenterLinePos[m_CenterLinePos.size()];
自分の間違いなので修正しておきます

2017-01-28 06:34 UTC, Keitaro0408 commented
指摘箇所を修正しました。
確認お願いします

2017-01-28 07:34 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/SceneBase/GameScene/ObjectManager/GamaObjectManager/RoadManager/Road/Road.h
> +	 * @param _pEndPos 道の終点
引数のin outが抜けてます

2017-01-28 07:36 UTC, Moto0116 commented
確認しました。
競合だけ解決してください。

2017-01-28 07:46 UTC, Keitaro0408 commented
競合解決とコミット整理を行いました。
合流お願いします

2017-01-30 05:24 UTC, Moto0116 approved these changes
確認しました
合流しておきます

2017-01-30 05:24 UTC, merged