11月版のmaster更新
KingdomCraft-1/KingdomCraft pull request #75
Opened 2016-11-03 09:26 UTC by Moto0116

11月バージョンにmasterを更新するプルリクエスト

問題がないようならチェックして、最後にチェックした人がマージお願いします。
- [ ] @Moto0116  
- [ ] @Keitaro0408

2016-11-03 10:01 UTC, taishi-matsumura requested changes
こんなコミットログがmasterの履歴にドーンと乗るのはさすがにイヤすぎるので整理して欲しいです。
developでの各作業はしっかりレビューもされていると思うので、履歴整理後のものとdevelopの最新との差分が無ければmergeしちゃって良いと思います。

2016-11-03 11:19 UTC, taishi-matsumura commented
rebase大変そうなので僕の方でちょっとやりましょか？

2016-11-03 11:43 UTC, Moto0116 commented
すみません、お願いしていいですか？

2016-11-03 13:17 UTC, taishi-matsumura commented
pull #80 で纏めてみましたので確認お願いします。

2016-11-03 14:33 UTC, taishi-matsumura commented
ログを纏めてforce pushしました。
ローカルのdevelopブランチでadddb8c(masterの最新)までreset hardしてからpullし直して下さい。

誰か、承認のレビューコメントとmasterへのmergeお願いします。

2016-11-03 14:50 UTC, Moto0116 commented
@Keitaro0408 自分プルリク作成者やったからレビューお願いします…

2016-11-03 14:58 UTC, taishi-matsumura commented
過去改変前のdevelopブランチの内容を取り直したい場合は、SourceTreeのブランチボタンから「指定のコミット」ってラジオボタンを選ぶと取ってこれます。
(コミット情報は永遠に残るというのは本当みたいです)

ローカルに適当な名前で新規ブランチ作って、そこに取ってくれば良いと思います。
一応「20161103」っていうtagも打っておきました。
ハッシュは 7fc2f21 です。

2016-11-03 15:47 UTC, taishi-matsumura approved these changes

2016-11-04 05:03 UTC, merged

2016-11-04 05:05 UTC, Moto0116 commented
承認されていたのでマージしておきました。