TitleSceneクラスとその配下の作成
KingdomCraft-1/KingdomCraft pull request #81
Opened 2016-11-07 02:19 UTC by Moto0116

**追加機能**
 - TitleSceneクラス
 - 配下クラス

issue #58

2016-11-13 08:48 UTC, Moto0116 commented
タイトルからゲームへの遷移
ロゴの表示
背景の表示
ボタンの追加
を行いました、レビューお願いします。

セーブデータ関係も突っ込むとこのプルリクのやることが大きいので、別のプルリクでやるつもりです。

2016-11-17 00:58 UTC, taishi-matsumura requested changes
全部は見てないですが、ひとまず。

2016-11-17 00:58 UTC, taishi-matsumura commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +m_IsTextureLoad(false)
`m_TextureKey`は初期化しないの？

2016-11-17 00:58 UTC, taishi-matsumura commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +	if (m_IsTextureLoad)
「ロードされているか」という意味のフラグなら、`m_IsTextureLoaded`と受け身にした方が良いですね。
あと、わざわざフラグを用意せずに`m_TextureKey`を使ってどうにかできないもんですか？

2016-11-17 00:58 UTC, taishi-matsumura commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.h
> +class TitleBackground
コピーコンストラクタと代入演算子が不要なクラスは、安全のために蓋してしまいましょう。
旧ドラキンで松村が作ったクラスでは多分やっていたと思います。
[Google C++スタイルガイド](http://www.textdrop.net/google-styleguide-ja/cppguide.xml#%E3%82%B3%E3%83%94%E3%83%BC%E3%82%B3%E3%83%B3%E3%82%B9%E3%83%88%E3%83%A9%E3%82%AF%E3%82%BF)なんかを参考にして下さい。

2016-11-17 00:58 UTC, taishi-matsumura commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleLogo/TitleLogo.cpp
> +	if (TextureManager::GetInstance()->LoadTexture(TEXT("Resource/Texture/TitleScene/TitleLogo/TitleLogo.png"), &m_TextureKey))
pathの区切り文字、`/`でいけるんですね。知りませんでした。

けどヘッダファイルのpathは`\`で区切るの？

2016-11-17 01:39 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleLogo/TitleLogo.cpp
> +	if (TextureManager::GetInstance()->LoadTexture(TEXT("Resource/Texture/TitleScene/TitleLogo/TitleLogo.png"), &m_TextureKey))
確かにその通りです。
path関係は`\`で統一しておきます。

2016-11-17 01:46 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +	if (m_IsTextureLoad)
そうですね。
そもそもTextureManager側で、読み込みが失敗した場合は空のテクスチャへのkeyを返すようにしといたら、ifなんて必要ないですよね…
修正しておきます。

2016-11-17 01:46 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +m_IsTextureLoad(false)
エラー値で初期化するようにしておきます。

2016-11-17 05:43 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.h
> +class TitleBackground
TitleScene配下のクラスはコピーコンストラクタと代入演算子を禁止しておきました。

2016-11-17 05:49 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +	if (m_IsTextureLoad)
`m_IsTextureLoad`は削除して、エラー時に行っていた処理はTextureManagerクラスに投げるように修正しました。

2016-11-17 06:03 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +m_IsTextureLoad(false)
`m_TextureKey`は-1で初期化するように修正しました。

2016-11-17 07:23 UTC, taishi-matsumura requested changes

2016-11-17 07:23 UTC, taishi-matsumura commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +m_TextureKey(-1)
`-1`というマジックナンバーが気持ち悪くてライブラリ掘ってみました。
keyというからmapなのかと思いきやvectorなんですね…
だったらkeyじゃなくてindexとかの方がいいし、いずれにせよマジックナンバーはイヤです。

2016-11-17 07:30 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleBackground/TitleBackground.cpp
> +m_TextureKey(-1)
すみません、indexじゃなくてkeyなのは確かにまぎらわしかったです、すぐに修正しておきます。

-1のマジックナンバーはTextureManagerクラスのほうに定数を作るべきだと思ったんで仮置きのつもりでした、コメントつけておきます。

2016-11-17 08:40 UTC, taishi-matsumura reviewed
key→indexへの変数名修正、確認しました。
vectorで怖いのは、例えば
「アプリ側はindexが5だと思っていたら、途中で3がeraseされて知らぬ間に自分のテクスチャは4になっていた」
みたいなパターンですがテクスチャに関してはそういう可能性は無いんでしたっけ？

マジックナンバー対応はライブラリ側修正時だと思っていたのでこれで問題ありません。
`@todo`はgood。

2016-11-17 12:44 UTC, Moto0116 commented
TextureManagerではインデックス番号を途中から変えたりはしないので大丈夫だと思います。

2016-11-17 12:52 UTC, Moto0116 commented
すみません、TitleSceneのデストラクタで解放処理を忘れていたので追加しました…

2016-11-17 12:53 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleScene.cpp
> +	FbxFileManager::GetInstance()->ClearBuffer();
@taishi-matsumura すみません、少し意見を聞きたいんですけど、TitleSceneのデストラクタでテクスチャとかシェーダーのバッファを解放するのってどう思いますか？

2016-11-18 00:44 UTC, taishi-matsumura commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleScene.cpp
> +	FbxFileManager::GetInstance()->ClearBuffer();
基本は「作った人が消す」ですが、基本から外れるケースはもちろん存在します。
なので、理由があれば良いのでは？

2016-11-18 00:44 UTC, taishi-matsumura approved these changes

2016-11-18 00:50 UTC, merged

2016-11-18 02:04 UTC, masami-sugao reviewed
見ている間にマージされちゃいましたが、折角見たのでコメントだけ残しておきます。
参考になれば。

2016-11-18 02:04 UTC, masami-sugao commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleMenu.cpp
> +	TitleMenu::MENU_ID MenuID = NONE_ID;
ローカル変数なのにパスカルケースのものが何個かありますが、データ型で分けているのでしょうか？

2016-11-18 02:04 UTC, masami-sugao commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleMenu.cpp
> +	bool isContinueButtonOn = m_pContinueButton->Control();
`isStartButtonOn`と`isContinueButtonOn`が共にtrueになることってあるのでしょうか？
あり得ないのであれば、優先する方を先にチェックして一方がtrueだったらもう一方はチェックしないようにした方が処理効率がよいように思います。

2016-11-18 02:04 UTC, masami-sugao commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleMenuButton/TitleMenuButton.cpp
> +	return isClick;
`OnClick`という名前だとクリックされたときの処理のように感じるので、クリックされたかどうかの判定処理にこの名前が付いているのは紛らわしいと思います。

2016-11-18 02:04 UTC, masami-sugao commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleSaveDataMenu/TitleSaveDataMenu.cpp
> +			MenuID = STARTGAME_ID;
`SaveDataMenuButton::Control()`が1つでもtrueの場合は`m_pSaveDataButton`の他の要素に対する処理が不要なのであれば、ここでループを抜けるようにした方がよいですね。

2016-11-18 02:04 UTC, masami-sugao commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleSaveDataMenu/TitleSaveDataButton/TitleSaveDataButton.h
> +	 * @param[in] _textureName 描画するボタンの画像
コメント修正漏れ

2016-11-18 02:04 UTC, masami-sugao commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleSaveDataMenu/TitleSaveDataButton/TitleSaveDataButton.cpp
> +TitleSaveDataButton::TitleSaveDataButton(const D3DXVECTOR2* const _pDrawPos, const D3DXVECTOR2* const _pDrawSize, LPCTSTR const _pTextureName) :
引数の型名と引数名の前両方に`const`が付いているのはどういう意味があるのですか？

2016-11-18 02:28 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleMenu.cpp
> +	TitleMenu::MENU_ID MenuID = NONE_ID;
このプロジェクトはデータ型やスコープにかかわらずパスカルケースで統一するようにしています。
なのでisStartButtonOnとかのほうが間違ってました…
#152のほうで修正します。

2016-11-18 02:31 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleSaveDataMenu/TitleSaveDataButton/TitleSaveDataButton.h
> +	 * @param[in] _textureName 描画するボタンの画像
教えていただきありがとうございます。
修正しておきます。

2016-11-18 02:33 UTC, Moto0116 commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleMenuButton/TitleMenuButton.cpp
> +	return isClick;
確かに紛らわしかったです。
`IsClicked`にでも修正しておきます。

2016-11-18 02:53 UTC, masami-sugao commented on src/KingdomCraft/KingdomCraft/Main/SceneManager/Scene/TitleScene/TitleMenu/TitleSaveDataMenu/TitleSaveDataButton/TitleSaveDataButton.cpp
> +TitleSaveDataButton::TitleSaveDataButton(const D3DXVECTOR2* const _pDrawPos, const D3DXVECTOR2* const _pDrawSize, LPCTSTR const _pTextureName) :
理解しました。どうもですー。
引数特有の仕様かと思ったので持ち合わせた時間内では見付けられずでした。